# Settings of application
spring.application.name=expense

# Settings of swagger documentation
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Log settings
logging.level.root=DEBUG
logging.config=classpath:logback-spring.xml

# Storage config
storage.type=dev